- name: "Check {{ ACTION }} -> {{ PROJ }}"
  shell: echo "ansible start ..."

# include vars
- name: " include variables "
  include_vars: "{{ PROJ }}.yml"

- name: "create app ({{ HOST_ARTI }}) dir if not exsiting"
  file: path={{ BASE_DIR }}/{{ PROJ }}/{{ HOST_ARTI }} state=directory

- name: "copy .ossutilconfig if not found"
  copy: src=.ossutilconfig dest=/root/ force=no

- name: "copy ossutil64 if not found"
  copy: src=ossutil64 dest=/usr/bin mode=755 force=no

- name: "download {{ PROJ }}.tar.gz from oss"
  shell: "{{ OSS_BIN }} cp --update {{ OSS_TAR_DIR }}/{{ PROJ }}.tar.gz {{ ARTI_DIR }}/{{ PROJ }}.tar.gz"

- name: "unarchive {{ ARTI_DIR }}/{{ PROJ }}.tar.gz to {{ BASE_DIR }}/"
  unarchive: 
    src : "{{ ARTI_DIR }}/{{ PROJ }}.tar.gz"
    dest: "{{ BASE_DIR }}"
    remote_src: yes
    mode: 755
    owner: nginx 
    group: nginx

- include_tasks: upgrade.yml
  when: ACTION == "upgrade"

- include_tasks: init.yml
  when: ACTION == "init"
