## 方式一：通过模版的方式（将backup.j2放于templates下），
## 使用这种方式的话应该放在init里，免得每次都要执行（因为模版需要参数进行渲染将模版文件中的变量进行替换）
#- name: " create backup script dir"
#  file: path=/tmp/deploy-backup state=directory
#- name: "copy deploy-backup script"
#  template: src=backup.j2 dest=/tmp/deploy-backup/{{ PROJ }}.sh mode=755
#- name: "exec backup script"
#  shell: /tmp/deploy-backup/{{ PROJ }}.sh

# 方式二：通过shell文件传参的方式（将backup.j2放于files下）
- name: "backup webui"
  script: backup.sh  {{ BASE_DIR }}/backup {{ PROJ }}
- name: "alter dir name"
  shell: rm -rf {{ BASE_DIR }}/{{ PROJ }} && mv {{ BASE_DIR }}/dist {{ BASE_DIR }}/{{ PROJ }} && chmod -R 755 {{ BASE_DIR }}/{{ PROJ }}
