- name: check chia {{ PARAM }} >= {{ P1 }} is running
  command:  p=$(ps aux |grep {{ PARAM }} |wc -l) && [[ "$p" -ge "{{ P1 }}" ]] && echo "success" || echo "failure"
  # ignore_errors: yes
  register: command_result
  failed_when: "'failure' in command_result.stderr"