- name: check chia [ {{ PARAM }} ] is running
  shell:  pgrep -f {{ PARAM }} >/dev/null 
  register: chia_ps
  failed_when: chia_ps.rc == 1
  changed_when: chia_ps.rc == 0

- debug:
    msg: "chia_ps.rc = {{ chia_ps.rc }}"