- name: check chia {{ PARAM }} >= {{ P1 }} is running
  shell:  p=$(ps aux |grep {{ PARAM }} |wc -l) && [[ "$p" -ge "{{ P1 }}" ]] && echo "success" || echo "failure"
  # ignore_errors: yes
  register: chia_status
  failed_when: "'success' not in chia_status.stdout"