- name: check chia [ {{ PARAM }} ] is running
  shell:  ps aux | grep {{ PARAM }} | wc -l
  # ignore_errors: yes
  register: chia_ps
  failed_when: chia_ps.stdout == 1

- debug: msg="chia_ps: {{ chia_ps.stdout }} - {{ chia_ps.stderr }}"