- name: check chia -{{ PARAM }}- is running
  shell:  p=$(ps aux |grep {{ PARAM }} |wc -l) && [[ "$p" -ge "{{ P1 }}" ]] && echo "success" || echo "failure"
  ignore_errors: yes
  changed_when: false
  register: chia_status

- name: Report status of chia -{{ PARAM }}-
  fail:
    msg: |
      chia-{{ PARAM }}- not fully launched!
  when: chia_status