- name: check chia [ {{ PARAM }} ] is running
  shell:  pgrep -f {{ PARAM }} >/dev/null 
  register: chia_ps
  failed_when: chia_ps.rc == 1
  changed_when: chia_ps.rc == 0

- debug:
    msg: "chia_ps.rc = {{ chia_ps.rc }}"

- hosts: all
  gather_facts: false
  tasks:
    - block:
        - wait_for_connection:
            sleep: 1
            timeout: 10
      rescue:
        - debug:
            msg: "{{ inventory_hostname }} not connected. End of host."
        - meta: clear_host_errors
        - meta: end_host

    - debug:
        msg: "{{ inventory_hostname }} is running"
    - setup:
