- name: check chia-plot is running
  shell:  $(ps aux |grep plots |wc -l) -eq 3 && echo "success" || echo "failure"
  ignore_errors: yes
  changed_when: false
  register: chia_plot_status

- name: Report status of chia-plot
  fail:
    msg: |
      chia-plot not fully launched!
  when: chia_plot_status