- name: check reachable hosts via ping
  gather_facts: no
  tasks:
    - command: ping -c1 {{ ansible_host }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: yes
    - group_by: key=reachable
      when: ping_result|success

- name: check reachable hosts via ssh port
  gather_facts: no
  tasks:
    - wait_for: host=remote.host port=22 timeout=1
    - debug: msg=ok