- name: reboot {{ inventory_hostname }}
  shell: reboot
  become: true
  when: PARAM == "reboot"

- name: umount {{ PARAM2 }}
  shell: mount |grep {{ PARAM2 }} && umount {{ PARAM2 }}  || echo "none umounted"
  become: true
  when: PARAM == "umount"

- name: rm -rf {{ PARAM2 }}
  command: rm -rf {{ PARAM2 }}
  become: true
  when: PARAM == "rm"

- name: rm ray lines in /etc/fstab
  command: sed -i '/ray/d' /etc/fstab 
  become: true
  when: PARAM == "clean"

- name: format /dev/sda
  command: mkfs.ext4 -F /dev/sda
  become: true
  when: PARAM == "format"

- name: format /dev/sdb
  command: mkfs.ext4 -F /dev/sdb
  become: true
  when: PARAM == "format"

- name: mount all
  command: mount -av
  become: true
  when: PARAM == "format"