- name: reboot {{ inventory_hostname }}
  shell: reboot
  become: true
  when: PARAM == "reboot"

- name: inject fstab - {{ P1 }} -> /media/ray/{{ P2 }}
  shell: cat /etc/fstab |grep {{ P2 }} || echo "/dev/{{ P1 }} /media/ray/{{ P2 }} ext4 defaults 0 0" >> /etc/fstab
  become: true
  when: PARAM == fstab

- name: add data2
  shell: cat /etc/fstab |grep data2 || echo "/dev/sdb /media/ray/data2 ext4 defaults 0 0" >> /etc/fstab
  become: true
  when: PARAM == data2

- name: umount {{ P1 }}
  shell: mount |grep {{ P1 }} && umount {{ P1 }}  || echo "none umounted"
  become: true
  when: PARAM == "umount"

- name: rm -rf {{ P1 }}
  command: rm -rf {{ P1 }}
  become: true
  when: PARAM == "rm"

- name: rm ray lines in /etc/fstab
  command: sed -i '/ray/d' /etc/fstab 
  become: true
  when: PARAM == "clean"

- name: format /dev/sda
  command: mkfs.ext4 -F /dev/sda
  become: true
  when: PARAM == "format"

- name: format /dev/sdb
  command: mkfs.ext4 -F /dev/sdb
  become: true
  when: PARAM == "format"

- name: mount all
  command: mount -av
  become: true
  when: PARAM == "format"