# - name: Check if PARAM is given
#   debug:
#     msg: "'{{ lookup('env', 'PARAM') }}' is the PARAM environment variable."

- name: kill all join_pool
  shell: killall hpool-miner-chia || echo "none hpool to kill"
  become: true
  ignore_errors: yes
  
- name: "copy chia_join_hpool.sh to ~/{{ inventory_hostname }} "
  copy: src=chia_join_hpool.sh dest=~/{{ inventory_hostname }}/ mode=755 force=yes

- name: "copy hpool-miner-chia to ~/{{ inventory_hostname }} "
  copy: src=hpool/hpool-miner-chia dest=~/{{ inventory_hostname }}/ mode=755 force=yes

- name: "generate hpool config.yml"
  template: src=hpool_config.j2 dest=~/{{ inventory_hostname }}/hpool_conf.yml force=yes

- name: "join hpool to mine XCH :-)"
  shell: ~/{{ inventory_hostname }}/chia_join_hpool.sh {{ inventory_hostname }}
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0