# clean docker container
- name: "initialize {{ inventory_hostname }}'s env"
  script: init.sh {{ inventory_hostname }}

- name: "add {{ mne }} to {{ inventory_hostname }}"
  command: echo "{{ mne }}" > ~/{{ inventory_hostname }}/mne

- name: "add API key [ {{ apikey }} ] to {{ inventory_hostname }}"
  command: echo "{{ apikey }}" > ~/{{ inventory_hostname }}/apikey

- name: "Add API Key to chia env"
  script: chia_add_key.sh {{ inventory_hostname }}