# clean docker container
- name: "initialize env [ {{ ansible_host }} ]"
  script: init.sh {{ ansible_host }}

- name: "add mne to {{ ansible_host }}"
  command: echo "{{ mne }}" > ~/{{ ansible_host }}/{{ ansible_host }}.mne
  with_items: groups["{{ ansible_host }}"]

- name: "add API key [ {{ apikey }} ] to {{ ansible_host }}"
  command: echo "{{ apikey }}" > ~/{{ ansible_host }}/{{ ansible_host }}.apikey
  with_items: groups["{{ ansible_host }}"]

- name: "Add API Key to chia env"
  script: chia_add_key.sh {{ ansible_host }}