- name: "initialize {{ inventory_hostname }}'s env"
  script: init.sh {{ inventory_hostname }} {{ CHIA_RELEASE_TAG }}

# create mnemonics file
- name: "add mne to {{ inventory_hostname }}"
  copy: 
    dest: ~/{{ inventory_hostname }}/mne
    content: "{{ hostvars[inventory_hostname].mne }}"
    force: yes

- name: "add API key [ {{ hostvars[inventory_hostname].apikey }} ] to {{ inventory_hostname }}"
  copy:
    dest: ~/{{ inventory_hostname }}/apikey
    content: "{{ hostvars[inventory_hostname].apikey }}"
    force: yes

- name: "import wallet mnecode into chia"
  script: chia_add_key.sh {{ inventory_hostname }} 
