# clean docker container
- name: "initialize {{ inventory_hostname }}'s env"
  script: init.sh {{ inventory_hostname }}

- name: "add mne to {{ inventory_hostname }}"
  command: echo "{{ mne }}" > ~/{{ inventory_hostname }}/{{ inventory_hostname }}.mne
  with_items: groups["{{ inventory_hostname }}"]

- name: "add API key [ {{ apikey }} ] to {{ inventory_hostname }}"
  command: echo "{{ apikey }}" > ~/{{ inventory_hostname }}/{{ inventory_hostname }}.apikey
  with_items: groups["{{ inventory_hostname }}"]

- name: "Add API Key to chia env"
  script: chia_add_key.sh {{ inventory_hostname }}