- name: create ext4 for ssd
  filesystem:
    fstype: ext4
    dev: /dev/nvme1n1
    force: yes
  become: true

- name: create ext4 for sda
  filesystem:
    fstype: ext4
    dev: /dev/sda
  become: true
  async: 600               # 10 mins
  poll: 0

- name: create ext4 for sdb
  filesystem:
    fstype: ext4
    dev: /dev/sdb
  become: true
  async: 600               # 10 mins
  poll: 0

- name: create data mount points
  shell: mkdir -p /media/ray/ssd && chown ray. /media/ray/ssd
  become: true
  async: 600               # 10 mins
  poll: 0