# clean docker container
- name: "initialize env: {{ ansible_hostname }}"
  script: init.sh {{ ansible_hostname }}

- name: "add mne to {{ ansible_hostname }}"
  command: echo "{{ mne }}" > ~/{{ ansible_hostname }}/{{ ansible_hostname }}.mne
  with_items: groups["{{ ansible_hostname }}"]

- name: "add API key [ {{ apikey }} ] to {{ ansible_hostname }}"
  command: echo "{{ apikey }}" > ~/{{ ansible_hostname }}/{{ ansible_hostname }}.apikey
  with_items: groups["{{ ansible_hostname }}"]

- name: "Add API Key to chia env"
  script: chia_add_key.sh {{ ansible_hostname }}