# clean docker container
- name: "add mne to {{ inventory_hostname }}"
  copy: 
    dest: ~/{{ inventory_hostname }}/mne
    content: "{{ hostvars[inventory_hostname].mne }}"

- name: "add API key [ {{ hostvars[inventory_hostname].apikey }} ] to {{ inventory_hostname }}"
  copy:
    dest: ~/{{ inventory_hostname }}/apikey
    content: "{{ hostvars[inventory_hostname].apikey }}"

- name: "initialize {{ inventory_hostname }}'s env"
  script: init.sh {{ inventory_hostname }} {{ CHIA_RELEASE_TAG }}