- name: create ext4 for ssd
  community.general.filesystem:
    fstype: ext4
    dev: /dev/nvme1n1
    state: absent
    force: yes
  become: true

- name: create ext4 for sda
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sda
    state: absent
    force: yes
  become: true
  async: 600               # 10 mins
  poll: 0

- name: create ext4 for sdb
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb
    state: absent
  become: true
  async: 600               # 10 mins
  poll: 0

- name: create data mount points
  shell: mkdir -p /media/ray/ssd && chown ray. /media/ray/ssd
  become: true
  async: 600               # 10 mins
  poll: 0