- name: create ext4 for ssd
  filesystem:
    fstype: ext4
    dev: /dev/nvme1n1
    opts: -cc
    force: yes

- name: create ext4 for sda
  filesystem:
    fstype: ext4
    dev: /dev/sda
    opts: -cc

- name: create ext4 for sdb
  filesystem:
    fstype: ext4
    dev: /dev/sdb
    opts: -cc

- name: create data mount points
  shell: sudo mkdir -p /media/ray/ssd && sudo chown ray. /media/ray/ssd