- include_tasks: checkhost.yml
  when: ACTION == "checkhost"
  
- include_tasks: fixdisk.yml
  when: ACTION == "fixdisk"

- include_tasks: initdisk.yml
  when: ACTION == "initdisk"
  
- include_tasks: init.yml
  when: ACTION == "init"

- include_tasks: plot.yml
  when: ACTION == "plot"

- include_tasks: joinpool.yml
  when: ACTION == "joinpool"