- include_tasks: initdisk.yml
  when: ACTION == "initdisk"
  
- include_tasks: init.yml
  when: ACTION == "init"

- include_tasks: plot.yml
  when: ACTION == "plot"

- include_tasks: upgrade.yml
  when: ACTION == "up" or ACTION == "upgrade" 