- include_tasks: check.yml
  when: ACTION == "check"
  
- include_tasks: fix.yml
  when: ACTION == "fix"

- include_tasks: initdisk.yml
  when: ACTION == "initdisk"
  
- include_tasks: init.yml
  when: ACTION == "init"

- include_tasks: plot.yml
  when: ACTION == "plot"

- include_tasks: plotrad.yml
  when: ACTION == "plotrad"

- include_tasks: hpool.yml
  when: ACTION == "hpool"

- include_tasks: ping.yml
  when: ACTION == "ping"