
- name: "generate plot.conf"
  template: src=plot_conf.j2 dest=~/{{ inventory_hostname }}/plot.conf force=yes

- name: "copy chia_plot_data.sh to ~/{{ inventory_hostname }} "
  copy: src=chia_plot_data.sh dest=~/{{ inventory_hostname }} mode=755 force=yes

- name: "copy chia_plot_data_batch.sh to ~/{{ inventory_hostname }} "
  copy: src=chia_plot_data_batch.sh dest=~/{{ inventory_hostname }} mode=755 force=yes

- name: "clean previous plotting tasks"
  shell: pkill chia || echo "none chia ps to kill"
  
- name: "clean previous temp files"
  shell: rm -rf /media/ray/ssd/*.tmp || echo "none tmpe file to clean"

- name: Batch run plotting now...
  shell: "(nohup ~/{{ inventory_hostname }}/chia_plot_data_batch.sh &)"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0
  # register: result

# - name: get previous result
#   debug:
#     var: result
    # verbosity: 2