
- name: "generate plotman.yaml"
  template: src=plotman.j2 dest=~/.config/plotman/plotman.yaml force=yes

- name: "create dir ~/{{ inventory_hostname }}"
  shell: mkdir -p ~/{{ inventory_hostname }}
  
- name: "copy plotman.sh to ~/{{ inventory_hostname }} "
  copy: src=plotman.sh dest=~/{{ inventory_hostname }} mode=755 force=yes

#- name: "clean previous temp dirs"
#  shell: rm -rf /media/ray/ssd/tmp* || echo "none temp dir to clean"

- name: Run plotman now...
  shell: bash ~/{{ inventory_hostname }}/plotman.sh
  async: 36000000 #10000 hours
  poll: 10  # 10 seconds
  register: result

- name: get previous result
  debug:
    var: result.stdout_lines
    verbosity: 2