- name: Plot data :#1
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh {{ inventory_hostname }} {{ ssd_dir }} {{ data_dir }} 1 4000 32)"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0