- name: Plot data1 :#1
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh {{ inventory_hostname }} {{ hostvars[inventory_hostname].ssd }} {{ hostvars[inventory_hostname].data1 }} {{ hostvars[inventory_hostname].rounds }} 9800 33)"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0
  register: result

- name: get previous result
  debug:
    var: result
    verbosity: 2

- name: Plot data1 :#2
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh {{ inventory_hostname }} {{ hostvars[inventory_hostname].ssd }} {{ hostvars[inventory_hostname].data1 }} {{ hostvars[inventory_hostname].rounds }} 9800 33)"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0

- name: Plot data2 :#1
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh {{ inventory_hostname }} {{ hostvars[inventory_hostname].ssd }} {{ hostvars[inventory_hostname].data2 }} {{ hostvars[inventory_hostname].rounds }} 9800 33)"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0