
- name: "create dir ~/{{ inventory_hostname }}"
  shell: mkdir -p ~/{{ inventory_hostname }}
  
- name: "create plotman logs dir"
  shell: mkdir -p ~/{{ inventory_hostname }}/plotman/logs

- name: "generate plotman.yaml"
  template: src=plotman.j2 dest=~/.config/plotman/plotman.yaml force=yes

- name: "clean temp files"
  shell: rm -rf {{ item }}/* || echo "none temp dir to clean"
  loop: "{{ hostvars[inventory_hostname].tmpPathArr }}"
  when: PARAM == "cleantmp"

- name: create tmp dirs
  shell: sudo mkdir -p {{ item }} && sudo chown {{ ansible_user }}. {{ item }}
  loop: "{{ hostvars[inventory_hostname].tmpPathArr }}"

- name: "copy plotman.sh to ~/{{ inventory_hostname }} "
  copy: src=plotman.sh dest=~/{{ inventory_hostname }} mode=755 force=yes


- name: kill all chia
  shell: killall chia || echo "non chia to kill"
  become: true
  ignore_errors: yes

- name: Run plotman now...
  shell: bash ~/{{ inventory_hostname }}/plotman.sh
  async: 36000000 #10000 hours
  poll: 5  # 10 seconds