- name: Plot data1 :#1
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh data1 {{ hostvars[inventory_hostname].plots }})"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0

- name: Plot data1 :#2
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh data1 {{ hostvars[inventory_hostname].plots }})"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0

- name: Plot data2 :#1
  shell: "(~/{{ inventory_hostname }}/chia_plot_data.sh data1 {{ hostvars[inventory_hostname].plots }})"
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0