environ:
  API_HOST_PORT: 21010
  API_INNER_PORT: 21010
  TASK_HOST_PORT: 31010
  TASK_PORT: 31010

  ## mysql #####
  DB_NAME: mgp-blockscan
  MYSQL_USERNAME: zwmini_rw
  MYSQL_PASSWORD: zwmini@123456
  
  ##### XXL-JOB ####
  TASK_JOB_ADMIN_URL: http://172.17.0.1:8888/xxl-job-admin
  TASK_APP_NAME: mgp-blockscan-task-executor
 # TASK_EXECUTOR_IP: "{{ HOST }}.vmi.ehex.me"
  TASK_EXECUTOR_IP: 172.17.0.1
  TASK_EXECUTOR_PORT: 31010

  ## MGP Node ##
  MGP_NODE: http://sh-expnode.vm.mgps.me:8888