environ:
  API_HOST_PORT: 21030
  API_INNER_PORT: 21030
  TASK_HOST_PORT: 31030
  TASK_PORT: 31030
  CONFIG_SVC_HOST: "{{ CONF_HOST }}"
  CONFIG_SVC_PORT: 22000

  ## mysql #####
  DB_NAME: mini-token-xswap
  MYSQL_USERNAME: zwmini_rw
  MYSQL_PASSWORD: zwmini@123456
  
  ##### XXL-JOB ####
  TASK_JOB_ADMIN_URL: http://172.17.0.1:8888/xxl-job-admin
  TASK_APP_NAME: token-xswap-task-executor
 # TASK_EXECUTOR_IP: "{{ HOST }}.vmi.ehex.me"
  TASK_EXECUTOR_IP: 172.17.0.1
  TASK_EXECUTOR_PORT: 31030

  ## MGP Node ##
  #MGP_NODE: http://sh-expnode.vm.mgps.me:8888
  MGP_NODE: http://sh-test.vm.mgps.me:8888