- name: chia ops playbook
  hosts: "{{ HOST }}"
  remote_user: ray
  roles:
  - deploy-chia
  vars:
    mount_dest_ssd: /media/ray/ssd
    mount_dest_data1: /media/ray/data1
    mount_dest_data2: /media/ray/data2